# Site Settings
title: "Movix â€“ Onderzoek naar beter openbaar vervoer in Nederland"

description: "Movix is een onafhankelijk ontwikkel- en onderzoeksproject dat onderzoekt hoe openbaar vervoer in Nederland toegankelijker, betaalbaarder en toekomstbestendiger kan worden."

url: "https://www.movix-ov.nl"
baseurl: ""

# SEO & Discovery Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Author Details
author:
  name: "Movix"
